const LOGIN = {
    INIT_AUTH: 'AUTH-INIT',
    AUTH_SUCCESS: 'AUTH-SUCCESS',
    AUTH_ERROR: 'AUTH-ERROR',
    LOGOUT: 'AUTH-LOGOUT'
}


const RESTAURANT = {
    LOAD_INIT: 'RESTAURANT_LOAD_INIT',
    LOAD_SUCCESS: 'RESTAURANT_LOAD_SUCCESS',
    LOAD_ERROR: 'RESTAURANT_LOAD_ERROR',
}

const COLLECTIONS = {
    LOAD_INIT: 'COLLECTIONS_LOAD_INIT',
    LOAD_SUCCESS: 'COLLECTIONS_LOAD_SUCCESS',
    LOAD_ERROR: 'COLLECTIONS_LOAD_ERROR',
}

const INVITATIONS = {
    LOAD_INIT: 'INVITATIONS_LOAD_INIT',
    LOAD_SUCCESS: 'INVITATIONS_LOAD_SUCCESS',
    LOAD_ERROR: 'INVITATIONS_LOAD_ERROR',
}


const COLLABORATE = {
    LOAD_INIT: 'COLLABORATE_LOAD_INIT',
    LOAD_SUCCESS: 'COLLABORATE_LOAD_SUCCESS',
    LOAD_ERROR: 'COLLABORATE_LOAD_ERROR',
}


export { LOGIN, RESTAURANT, COLLECTIONS, INVITATIONS, COLLABORATE }

