const LOGIN = {
    INIT_AUTH: 'AUTH-INIT',
    AUTH_SUCCESS: 'AUTH-SUCCESS',
    AUTH_ERROR: 'AUTH-ERROR',
    LOGOUT: 'AUTH-LOGOUT'
}

const REGISTER = {
    INIT_REGISTER: 'INIT-REGISTER',
    REGISTER_SUCCESS: 'SUCCESS-REGISTER',
    REGISTER_ERROR: 'REGISTER-ERROR'
}

export { LOGIN, REGISTER }

